/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.dinemore.client.view;

import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import lk.ijse.dinemore.client.connector.ServerConnector;
import lk.ijse.dinemore.client.observer.custom.impl.TelephoneOperatorObserverImpl;
import lk.ijse.dinemore.common.controller.TelephoneOperatorController;
import lk.ijse.dinemore.common.dto.OrderDTO;
import lk.ijse.dinemore.common.factory.ControllerFactory;

/**
 *
 * @author HP
 */
public class TelephoneOperatorView extends javax.swing.JFrame {

    private TelephoneOperatorObserverImpl telephoneOperatorObserverImpl;
    TelephoneOperatorController telephoneOperatorController;

    /**
     * Creates new form TelephoneOperatorView
     */
    public TelephoneOperatorView() {
        initComponents();
        setDateTime();
        try {
            telephoneOperatorObserverImpl = new TelephoneOperatorObserverImpl(this);
            ControllerFactory controllerFactory = ServerConnector.getInstance().getControllerFactory();
            telephoneOperatorController = controllerFactory.getTelephoneOperatorController();
            telephoneOperatorController.registerObserver(telephoneOperatorObserverImpl);
        } catch (Exception ex) {
            Logger.getLogger(TelephoneOperatorView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        comboOperatorID = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtOrderID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        btnOrderAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePendingOrdersTP = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtCustomerTelll = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTakenOrdersTP = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableFinishedOrdersTP = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblTPDate = new javax.swing.JLabel();
        lblTPTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(485, 520));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Operator ID : ");
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 120, -1));

        comboOperatorID.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        comboOperatorID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TP-001", "TP-002", "TP-003", "TP-004" }));
        comboOperatorID.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel2.add(comboOperatorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText("Order ID");
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(170, 40));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtOrderID.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtOrderID.setPreferredSize(new java.awt.Dimension(250, 40));
        txtOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setText("Customer Name");
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(170, 40));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtCustomerName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtCustomerName.setPreferredSize(new java.awt.Dimension(250, 40));
        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        btnOrderAdd.setBackground(new java.awt.Color(0, 153, 51));
        btnOrderAdd.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnOrderAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnOrderAdd.setText("Add");
        btnOrderAdd.setPreferredSize(new java.awt.Dimension(100, 40));
        btnOrderAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnOrderAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("  Pending Orders");
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 430, 40));

        tablePendingOrdersTP.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tablePendingOrdersTP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Qty", "Cust. Name", "Cust. Tel", "Added Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePendingOrdersTP.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tablePendingOrdersTP.setSelectionForeground(new java.awt.Color(0, 0, 102));
        jScrollPane1.setViewportView(tablePendingOrdersTP);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 430, 160));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setText("Customer Telephone");
        jLabel10.setOpaque(true);
        jLabel10.setPreferredSize(new java.awt.Dimension(170, 40));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtCustomerTelll.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtCustomerTelll.setPreferredSize(new java.awt.Dimension(250, 40));
        txtCustomerTelll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerTelllActionPerformed(evt);
            }
        });
        jPanel2.add(txtCustomerTelll, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        txtQty.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtQty.setPreferredSize(new java.awt.Dimension(250, 40));
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        jPanel2.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setText("Quantity");
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(170, 40));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 440, -1));

        jPanel3.setPreferredSize(new java.awt.Dimension(485, 520));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("  Taken Orders");
        jLabel7.setOpaque(true);
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 480, 40));

        tableTakenOrdersTP.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tableTakenOrdersTP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Qty", "Added", "Taken", "ChefID", "Cust. Name", "Cust. Tell"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTakenOrdersTP.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tableTakenOrdersTP.setSelectionForeground(new java.awt.Color(0, 0, 102));
        jScrollPane2.setViewportView(tableTakenOrdersTP);
        if (tableTakenOrdersTP.getColumnModel().getColumnCount() > 0) {
            tableTakenOrdersTP.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 710, 190));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("  Finished Orders");
        jLabel8.setOpaque(true);
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 480, 40));

        tableFinishedOrdersTP.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tableFinishedOrdersTP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Qty", "Added", "Taken", "Finished", "ChefID", "Cust. Name", "Cust. Tell"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFinishedOrdersTP.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tableFinishedOrdersTP.setSelectionForeground(new java.awt.Color(0, 0, 102));
        jScrollPane3.setViewportView(tableFinishedOrdersTP);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 710, 210));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 720, -1));

        jPanel4.setPreferredSize(new java.awt.Dimension(980, 50));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dinemore-Telephone Operator Area");
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(680, 50));
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        lblTPDate.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        lblTPDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTPDate.setOpaque(true);
        lblTPDate.setPreferredSize(new java.awt.Dimension(680, 50));
        jPanel4.add(lblTPDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 200, -1));

        lblTPTime.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        lblTPTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTPTime.setOpaque(true);
        lblTPTime.setPreferredSize(new java.awt.Dimension(680, 50));
        jPanel4.add(lblTPTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 220, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderIDActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void btnOrderAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderAddActionPerformed

        try {
            String orderID = txtOrderID.getText();
            int qty = Integer.parseInt(txtQty.getText());
            String custName = txtCustomerName.getText();
            String custTell = txtCustomerTelll.getText();
            String time = lblTPTime.getText();
            String date = lblTPDate.getText();
            String tpID = comboOperatorID.getSelectedItem().toString();
            OrderDTO orderDTO = new OrderDTO(orderID, custName, custTell, date, "Pending", qty, time, "not yet", "not Yet", tpID, "not Yet");
            boolean save = telephoneOperatorController.save(orderDTO);
            if (save) {
                JOptionPane.showMessageDialog(this, "Order Added");
            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }
            clearText();
        } catch (Exception ex) {
            Logger.getLogger(TelephoneOperatorView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOrderAddActionPerformed

    private void txtCustomerTelllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerTelllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerTelllActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelephoneOperatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelephoneOperatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelephoneOperatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelephoneOperatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelephoneOperatorView().setVisible(true);
            }
        });
    }

    public void updateTables() {

        DefaultTableModel dtm1 = (DefaultTableModel) tablePendingOrdersTP.getModel();
        dtm1.setRowCount(0);
        try {
            ArrayList<OrderDTO> allPendingOrders = telephoneOperatorController.getAllPendingOrders();

            for (OrderDTO order : allPendingOrders) {
                Object[] rowData = {
                    order.getOrderID(),
                    order.getQty(),
                    order.getCustomerName(),
                    order.getCustomerTel(),
                    order.getAddedTime()
                };
                dtm1.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(TelephoneOperatorView.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel dtm2 = (DefaultTableModel) tableTakenOrdersTP.getModel();
        dtm2.setRowCount(0);
        try {
            ArrayList<OrderDTO> allPendingOrders = telephoneOperatorController.getAllTakenOrders();

            for (OrderDTO order : allPendingOrders) {
                Object[] rowData = {
                    order.getOrderID(),
                    order.getQty(),
                    order.getAddedTime(),
                    order.getTakenTime(),
                    order.getChefID(),
                    order.getCustomerName(),
                    order.getCustomerTel()
                };
                dtm2.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(TelephoneOperatorView.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel dtm3 = (DefaultTableModel) tableFinishedOrdersTP.getModel();
        dtm3.setRowCount(0);
        try {
            ArrayList<OrderDTO> allPendingOrders = telephoneOperatorController.getAllFinishedOrders();

            for (OrderDTO order : allPendingOrders) {
                Object[] rowData = {
                    order.getOrderID(),
                    order.getQty(),
                    order.getAddedTime(),
                    order.getTakenTime(),
                    order.getFinishedTime(),
                    order.getChefID(),
                    order.getCustomerName(),
                    order.getCustomerTel()
                };
                dtm3.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(TelephoneOperatorView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrderAdd;
    private javax.swing.JComboBox<String> comboOperatorID;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTPDate;
    private javax.swing.JLabel lblTPTime;
    private javax.swing.JTable tableFinishedOrdersTP;
    private javax.swing.JTable tablePendingOrdersTP;
    private javax.swing.JTable tableTakenOrdersTP;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerTelll;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables

    private void clearText() {
        txtOrderID.setText("");
        txtCustomerName.setText("");
        txtCustomerTelll.setText("");
        txtQty.setText("");
    }

    public void setDateTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm a");
                lblTPTime.setText(timeFormat.format(date));
                SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
                lblTPDate.setText(dateFormat.format(date));
            }
        }
        ).start();
    }
}
